input {
  beats {
    port => 5044
  }
}

filter {
  json {
    source => "message"
    skip_on_invalid_json => true
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "echo-app-%{+YYYY.MM.dd}"
    retry_initial_interval => 5
    retry_max_interval => 60
  }
  stdout {
    codec => rubydebug
  }
}
